version: '2'
services:

  db:
    image: postgres:9.6
    env_file:
      - db.env
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    ports:
      - '5432'
    restart: always

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/var/lib/redis
    ports:
      - '6379'

  web:
    build: .
    command: /bin/bash -c "bundle install; bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - db.env
      - rails.env
      - redis.env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    restart: always

volumes:
  redis-data:
    driver: local
